// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qymzornljeueqekjyxvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5bXpvcm5samV1ZXFla2p5eHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NDk0MTIsImV4cCI6MjA4MzAyNTQxMn0.62FjWF3wCYqpoVBTHOSgue3hfXm4Ld9eyv6rt7AGEg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});